trigger: none

pool:
  vmImage: 'macOS-latest'

variables:
 - name: serviceConnection
   value: AppCenterConnection
 - name: appBucket
   value: Tesco-Pay-1/Pipeline-testing
 - name: groupId
   value: df4a749b-d29a-489b-ae0a-422ec2b60ba9
extends:
  template: templates/common.yaml
  parameters:
  releaseNotes: ''
    

      
